version: '3.3'

services:
  admin_service:
    container_name: admin_service
    build: 
      context: ./Admin
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - Task2-app
    restart: on-failure
    depends_on:
      - Admin_db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://Admin_db:27017

  Admin_db:
    image: mongo:3.6.19-xenial
    container_name: Admin_db
    ports:
      - "27080:27017"
    networks:
      - Task2-app
    volumes:
      - Admin-volume:/data/db

volumes:
  Admin-volume:

networks:
  Task2-app:
    driver: bridge
